language: generic
# Dependency of the minted package
before_install:
    - sudo apt-get install libfontconfig1-dev libgraphite2-dev libharfbuzz-dev libicu-dev libssl-dev zlib1g-dev cargo
    - cargo install tectonic
install:
    - tectonic main.tex
deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: ./main.pdf
    skip_cleanup: true
    on:
        tags: true
